### ISSUE TITLE
Add column bodyLanguage in messages table

### ISSUE THREAD

**Issue by multimob** [iNPUTmice/ceb2txt#5]
ceb2txt crashes with CEB files generated by recent versions of Conversations.

Output message: [SQLITE_ERROR] SQL error or missing database (table messages has no column named bodyLanguage)

Proposed fix: add one column to the "create database messages" statement in src/main/java/im/conversations/ceb2txt/Main.java

See patch here.
https://github.com/multimob/ceb2txt/compare/addbodylanguage?expand=1

**Comment by moppman** [comment]
I, too, encountered this problem and can confirm your patch fixed it @multimob . Thanks!
Maybe make a PR?

**Comment by Funatiker** [comment]
I also encountered the problem, saw that the column was missing, and was about to manually add it. Then I saw your branch at https://github.com/multimob/ceb2txt

It is exactly the change, I'd have tried. I ran the code you proposed. Worked fine. I highly recommend that you create a pull request so that @iNPUTmice can easily apply this patch.

**Comment by moppman** [comment]
I just made a PR because @multimob seems inactive and the issue makes ceb2txt disfunctional. 
Hope he doesn't mind :).

**Comment by multimob** [comment]
> I just made a PR because @multimob seems inactive and the issue makes ceb2txt disfunctional.
> Hope he doesn't mind :).

No problem.  Thanks for doing it.
